# Generated by Django 5.0.1 on 2024-01-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_type', models.CharField(choices=[('SS', 'Salt Spring'), ('O2', 'O2 Water'), ('MDS', 'Regular Water'), ('OZ', 'Ozone Water')], max_length=3, verbose_name='Water Type')),
                ('bottle_size', models.IntegerField(choices=[(3, 'Large (5 Gallon)'), (5, 'Small (3 Gallon)')], verbose_name='Bottle Size')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('water_type', 'bottle_size'), name='water_type_size'),
        ),
    ]
